// ---------------------------------------------------------------------------
// THE JOB DESCRIPTION, AS A DOCUMENT TO PRINT.
//
//   POST /api/admin/job-description/document  { positionId }  -> { ok, html }
//
// ---------------------------------------------------------------------------
// WHY THIS EXISTS
// ---------------------------------------------------------------------------
//
// Every appointment letter names a job description as Attachment 1 and says it
// "forms part of the official appointment record". `jobDescriptionDocument.ts`
// produces that document — and nothing called it, so the second document of the
// four-document appointment package could be generated by no screen and no
// route. A letter naming an attachment nobody can produce is a letter making a
// promise the University cannot keep.
//
// ---------------------------------------------------------------------------
// IT READS THE RESOLVED DOCUMENT, NOT THE POST'S OWN ROWS
// ---------------------------------------------------------------------------
//
// 048's `position_job_description` view applies the inheritance rule: a
// family's clause stands for a section unless this post restated that section,
// in which case the post's REPLACES it rather than joining it. Reading the raw
// clause rows and merging them here would be a second implementation of that
// rule, and the two would disagree the first time either changed.
//
// ---------------------------------------------------------------------------
// A DRAFT IS PRINTABLE, AND SAYS SO ON ITS FACE
// ---------------------------------------------------------------------------
//
// Refusing to print a draft would be the wrong call: a job description is
// circulated for comment before anybody approves it, and a University that
// cannot print the thing it is consulting on will produce it in a word
// processor instead — which is where all of this came from. So it prints, with
// a box at the top saying it is not in force and no appointment may be made
// against it.
// ---------------------------------------------------------------------------

import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { guard } from '@/lib/adminAuth';
import { supabaseUrl as SUPABASE_URL } from '@/lib/supabase';
import { UNIVERSITY } from '@/lib/constants';
import type { Capability } from '@/lib/roles';
import { FAMILY_LABELS, type PositionFamily } from '@/lib/positions';
import { jobDescriptionHtml, type JdClause } from '@/lib/jobDescriptionDocument';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const bad = (error: string, status: number, detail?: string) =>
  NextResponse.json({ ok: false, error, ...(detail ? { detail } : {}) }, { status });

type Row = Record<string, unknown>;

export async function POST(request: Request) {
  let body: Record<string, unknown>;
  try { body = await request.json(); } catch { return bad('bad-json', 400); }

  // THE SAME AUTHORITY THAT WRITES ONE. Printing a job description is reading
  // it, and the people who may read it are the people who work on it — 005
  // settled who decides what the University's documents say.
  const g = await guard(request, 'approve-credential-design' as Capability);
  if (!g.ok) return NextResponse.json({ ok: false, error: g.error }, { status: g.status });

  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!serviceKey) return bad('service-role-key-missing', 500);
  const admin = createClient(SUPABASE_URL, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const positionId = String(body.positionId ?? '');
  if (!positionId) return bad('no-position', 400);

  const { data: post } = await admin.from('positions')
    .select('id, job_code, title, family, unit_name, reports_to')
    .eq('id', positionId).maybeSingle();
  const po = post as Row | null;
  if (!po) return bad('position-not-found', 404);

  // THE VERSION IN FORCE, OR THE LATEST DRAFT. In that order, because the
  // question "what does this post's job description say" means the active one
  // wherever there is one.
  const { data: active } = await admin.from('position_profiles')
    .select('id, version, status, job_purpose, activated_at, activated_by')
    .eq('position_id', positionId).eq('status', 'active').maybeSingle();

  let profile = active as Row | null;
  if (!profile) {
    const { data: latest } = await admin.from('position_profiles')
      .select('id, version, status, job_purpose, activated_at, activated_by')
      .eq('position_id', positionId)
      .order('version', { ascending: false }).limit(1).maybeSingle();
    profile = latest as Row | null;
  }

  // ---------------------------------------------------------------------
  // A POST WITH NO PROFILE OF ITS OWN STILL HAS A JOB DESCRIPTION.
  //
  // 048's whole design is that a post inherits its family's, and most of the
  // forty-three posts have no profile of their own at all. Refusing here would
  // report "no job description" for a post whose job description the view can
  // produce perfectly well.
  // ---------------------------------------------------------------------
  const { data: rows } = await admin.from('position_job_description')
    .select('section, ordinal, body, source')
    .eq('position_id', positionId)
    .order('ordinal');
  const clauses = (rows ?? []) as unknown as JdClause[];

  if (clauses.length === 0) {
    return bad('nothing-to-print', 409,
      `${String(po.title)} has no job description yet — neither its own nor one from the `
      + `${FAMILY_LABELS[po.family as PositionFamily] ?? String(po.family)} family. Write one in `
      + 'Job Descriptions first; the letter that names it as an attachment cannot produce it '
      + 'until it exists.');
  }

  // WHO APPROVED IT, NAMED. Absent on a draft, and the document then prints no
  // signature block at all rather than a rule with nobody under it.
  let approvedByName: string | null = null;
  let approvedByRole: string | null = null;
  if (profile?.activated_by) {
    const { data: who } = await admin.from('profiles')
      .select('full_name, role').eq('id', profile.activated_by as string).maybeSingle();
    const w = who as Row | null;
    approvedByName = (w?.full_name as string | null) ?? null;
    approvedByRole = (w?.role as string | null) ?? null;
  }

  const doc = await jobDescriptionHtml({
    code: String(po.job_code),
    title: String(po.title),
    family: FAMILY_LABELS[po.family as PositionFamily] ?? (po.family as string | null),
    unit: (po.unit_name as string | null) ?? null,
    reportsTo: (po.reports_to as string | null) ?? null,
    jobPurpose: (profile?.job_purpose as string | null) ?? null,
    version: Number(profile?.version ?? 1),
    status: String(profile?.status ?? 'draft'),
    activatedOn: (profile?.activated_at as string | null)?.slice(0, 10) ?? null,
    approvedByName,
    approvedByRole,
    clauses,
    siteUrl: process.env.NEXT_PUBLIC_SITE_URL ?? `https://${UNIVERSITY.website}`,
    issuedOn: new Date().toISOString().slice(0, 10),
  });

  return NextResponse.json({
    ok: true,
    html: doc.html,
    reference: doc.reference,
    sealed: doc.seal?.sealed ?? false,
    inForce: profile?.status === 'active',
  });
}
