import { africanGlobeOfKnowledge } from '@/lib/credentialArt';
import { UNIVERSITY } from '@/lib/constants';
import HeroCopy from './HeroCopy';

// ---------------------------------------------------------------------------
// THE HERO.
//
// ===========================================================================
// WHY THERE IS NO PHOTOGRAPH HERE AT ALL
// ===========================================================================
//
// The first version stretched a photograph across the full width. The second
// kept one in a contained 440px frame. Both were judged poor, and the audit
// says why: the photography cannot carry a hero.
//
//   home-hero.jpg      972 × 729
//   global.jpg         972 × 729
//   students.jpg       968 × 648
//   every 2024 graduation photograph      1080 × 720
//
// Of ninety-seven photographs in this repository, THREE exceed 1600px wide, and
// two of those three are unusable for reasons worse than resolution:
// landing-bg.jpg is stock — hands on a laptop, nowhere in particular — and
// wp/footer-building.jpg is a CAMBRIDGE COLLEGE, an English quadrangle that sat
// in this university's asset folder and on its footer.
//
// Shrinking the frame fixed the sharpness and did not fix the picture. A single
// graduand photographed indoors on a phone, looking down, is a record of an
// occasion. It is not an image an institution leads with, and no crop makes it
// one. The honest conclusion is that this university does not yet own a
// photograph worth putting at the top of its front page.
//
// ===========================================================================
// WHAT IT LEADS WITH INSTEAD
// ===========================================================================
//
// Its own device. The figure below is generated by src/lib/credentialArt.ts —
// the guilloché rosette, the engraved world, the laurel, the microtext register
// — and it is the SAME artwork printed on every certificate this university
// issues. It is vector, so it is exact at any size on any display; it weighs a
// few kilobytes; and it is the one visual this institution unambiguously owns.
//
// A university leading with its own seal rather than with a photograph is not a
// compromise. It is what Oxford, Bologna and Salamanca did for several hundred
// years, and it is what a certificate does today: when an institution has
// something to attest, it puts its mark on it.
//
// WHEN THE PHOTOGRAPHS ARRIVE. One commissioned session — campus, classroom,
// library, faculty teaching, shot at 3000px or wider — and a photograph can
// take the right-hand side back. Until then this is stronger, and it is honest.
//
// ---------------------------------------------------------------------------
// WHY THIS IS A SERVER COMPONENT
//
// credentialArt.ts is about eighteen hundred lines of guilloché maths,
// coastline projection and microtext layout. It is pure and deterministic, so
// it runs ONCE here, on the server, and emits a string of SVG. Only the
// rotating headline is client code — see HeroCopy.tsx. Shipping the art module
// to the browser to draw something that never changes would be several hundred
// kilobytes spent on the first paint of the busiest page on the site.
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// WHY THE DEVICE IS DRAWN BARE, NOT SET IN THE ROSETTE
//
// deviceInRosette() puts the figure inside the guilloché band used on the
// certificate. On paper that is right: the band is the security ground and the
// device is what is set in it. On a screen it fails twice over.
//
// It costs two thirds of the frame. The band takes the outer 17% on each side
// and the device shrinks to 66% of the width — so in a 460px column the mark
// itself is barely 300px, and every hairline is 300/460 of the weight it could
// have been. That is precisely the wiriness this hero was accused of.
//
// And its ten-pointed silhouette reads as a spider, not a seal. The rosette is
// meant to be seen at certificate scale, where it is a fine engine-turned
// ground; blown up to a third of a viewport it becomes the loudest thing on the
// page and it is not the subject.
//
// So the hero takes the device alone, at full frame. Same artwork, same seed —
// the same figure the certificate carries at its centre — just given the whole
// width instead of a third of it.
//
// TIER 'full' RATHER THAN 'supreme'. Supreme adds an outer hatched register
// that at this size collides with the legend ring and reads as noise. Full
// keeps the legend, the laurel, the meridian web and the founding year, which
// is everything the figure actually says.
// ---------------------------------------------------------------------------

const DEVICE = africanGlobeOfKnowledge({
  // Fixed seed: the hero's figure must be the same drawing on every render and
  // every deployment. A random seed would give each visitor a different crest,
  // which is the opposite of what a mark is for.
  seed: 1907,
  // Size is a coordinate space, not an appearance. Every stroke width in
  // credentialArt.ts is (base * size) / 400, so the figure is self-similar:
  // doubling this and halving the CSS width gives a pixel-identical result.
  // Weight on screen comes from how wide the container is, not from here.
  size: 560,
  colour: '#f7dc79',
  legend: [UNIVERSITY.name.toUpperCase(), 'NOBILITY · PROFESSIONALISM · GODLINESS'],
  founded: String(UNIVERSITY.established),
  tier: 'full',
  style: 'seal',
  centre: 'globe',
  // The azimuthal equidistant world — the UN-emblem projection — rather than
  // the orthographic sphere. The sphere shows one hemisphere, which from
  // Africa's longitude means Africa and very little else; the flat world shows
  // every continent at once. For a university whose claim is that it is global,
  // that difference is the whole argument.
  world: 'flat',
  opacity: 1,
  holder: null,
});

export default function Hero() {
  return (
    <section
      data-on-dark=""
      aria-label="ICOF Global University"
      className="relative isolate overflow-hidden bg-brand-purple-dark text-white"
    >
      {/* ---- the engraved ground, entirely vector ------------------------ */}
      <div aria-hidden="true" className="absolute inset-0">
        <div
          className="absolute inset-0 opacity-[0.30]"
          style={{
            backgroundImage:
              'radial-gradient(ellipse 120% 90% at 20% 14%, rgba(120,102,186,0.55), transparent 60%),'
              + 'radial-gradient(ellipse 100% 80% at 84% 82%, rgba(233,193,74,0.18), transparent 62%),'
              + 'radial-gradient(ellipse 90% 70% at 58% 8%, rgba(64,44,104,0.9), transparent 70%)',
          }}
        />
        {/* Engine-turned rules — the ground the certificate is printed on. */}
        <div
          className="absolute inset-0 opacity-[0.07]"
          style={{ backgroundImage: 'repeating-linear-gradient(104deg, #f7dc79 0 1px, transparent 1px 22px)' }}
        />
        <div
          className="absolute inset-0 opacity-[0.05]"
          style={{ backgroundImage: 'repeating-linear-gradient(-104deg, #f7dc79 0 1px, transparent 1px 30px)' }}
        />
        <div className="absolute inset-0 bg-[radial-gradient(75%_60%_at_16%_0%,rgba(255,255,255,0.10),transparent_70%)]" />
        <div className="absolute inset-x-0 bottom-0 h-32 bg-gradient-to-b from-transparent to-brand-purple-dark" />
      </div>

      <div className="relative mx-auto grid max-w-6xl items-center gap-12 px-4 py-24 sm:px-6 sm:py-28 lg:grid-cols-[minmax(0,1.05fr)_minmax(0,460px)] lg:gap-16 lg:py-32">
        <HeroCopy />

        {/* ---- the device -------------------------------------------------
            Decorative here: everything it says in microtext — the university's
            name, the motto, the founding year — is set in readable type in the
            column beside it, so a screen reader that announced the figure would
            be reading the same words a second time. */}
        <div aria-hidden="true" className="relative mx-auto w-full max-w-[520px]">
          {/* The dark disc the device is struck on. Gold hairlines on a
              mid-purple field have very little to push against; dropping the
              ground beneath them by a couple of stops is what turns a wire
              drawing into an engraving. It is also why a wax seal is darker
              than the paper it sits on. */}
          <span
            className="absolute inset-[2%] rounded-full"
            style={{
              background:
                'radial-gradient(circle at 50% 46%, rgba(24,12,44,0.92) 0%, rgba(29,16,52,0.78) 52%, rgba(43,28,70,0.22) 78%, transparent 88%)',
            }}
          />

          {/* A slow counter-rotation of the outer glow only. The device itself
              never turns: a crest that spins is a logo animation, and this is a
              seal. */}
          <span
            className="absolute inset-[6%] animate-crest rounded-full opacity-50 blur-2xl"
            style={{
              background:
                'conic-gradient(from 0deg, transparent 0deg, rgba(247,220,121,0.5) 90deg, rgba(120,102,186,0.55) 200deg, transparent 300deg)',
            }}
          />

          {/* The bloom. A one-pixel gold line at this size is thinner than the
              eye reads as a line, so a tight drop-shadow in the same gold gives
              each stroke a hair of spread — the way a struck foil catches light
              at its edges. Two shadows: a close one for weight, a wide one for
              the halo. Cheap: no filter graph, no rasterised layer of its own
              beyond what the compositor already needs. */}
          <div
            className="relative [&>svg]:h-auto [&>svg]:w-full"
            style={{
              filter:
                'drop-shadow(0 0 1px rgba(247,220,121,0.55)) drop-shadow(0 0 14px rgba(233,193,74,0.22))',
            }}
            dangerouslySetInnerHTML={{ __html: DEVICE }}
          />
        </div>
      </div>
    </section>
  );
}
