'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import { heroSlides } from '@/content/site';
import { HERO_ASSURANCES } from '@/content/institutionalFacts';
import { UNIVERSITY } from '@/lib/constants';
import Magnetic from '@/components/Magnetic';

// ---------------------------------------------------------------------------
// The rotating half of the hero.
//
// WHY THIS IS SPLIT OUT OF Hero.tsx. The hero's visual anchor is the
// university's engraved device, generated by src/lib/credentialArt.ts — about
// eighteen hundred lines of guilloché maths, coastline projection and microtext
// layout. That module is pure and deterministic, so it can run once on the
// server and emit a string of SVG.
//
// If the hero were a single client component it would drag all of that into the
// browser bundle to produce artwork that never changes after the first paint.
// So the parent stays a Server Component and renders the device; only this
// small piece — a headline that rotates and a pause handler — is client code.
// ---------------------------------------------------------------------------

export default function HeroCopy() {
  const [line, setLine] = useState(0);
  const [reduced, setReduced] = useState(false);
  const [paused, setPaused] = useState(false);

  useEffect(() => {
    setReduced(window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  }, []);

  useEffect(() => {
    if (reduced || paused) return;
    const t = setInterval(() => setLine((l) => (l + 1) % heroSlides.length), 7000);
    return () => clearInterval(t);
  }, [reduced, paused]);

  const slide = heroSlides[line];

  return (
    // WCAG 2.2.2: the headline auto-updates, so it must be pausable. Focus
    // matters more than hover — a keyboard user tabbing to the call to action
    // otherwise gets the headline changing under the button they are aiming at.
    <div
      onMouseEnter={() => setPaused(true)}
      onMouseLeave={() => setPaused(false)}
      onFocusCapture={() => setPaused(true)}
      onBlurCapture={() => setPaused(false)}
    >
      <p className="font-heading text-[13px] font-bold uppercase tracking-[0.42em] text-white/85 sm:text-[15px] sm:tracking-[0.5em]">
        A Global University
      </p>

      <p className="mt-5 flex flex-wrap items-center gap-x-3 gap-y-1.5 font-sans text-[10px] font-semibold uppercase tracking-[0.22em] text-brand-gold sm:text-[11px] sm:tracking-[0.26em]">
        {UNIVERSITY.motto.replace(/&/g, '·').split(/[,·]/).map((word, wi) => (
          <span key={word} className="flex items-center gap-3">
            {wi > 0 && <span aria-hidden="true" className="h-1 w-1 rounded-full bg-brand-gold/70" />}
            {word.trim()}
          </span>
        ))}
      </p>

      <h1 className="mt-8 font-heading text-[clamp(2.5rem,6.6vw,5.2rem)] font-bold leading-[1.01] tracking-[-0.028em] text-transparent [background-image:linear-gradient(168deg,#ffffff_28%,#f7e6b4_70%,#e9c14a_100%)] [background-clip:text] [-webkit-background-clip:text] [text-wrap:balance]">
        {slide.title}
      </h1>

      <p className="mt-7 max-w-xl text-lg leading-relaxed text-white/80 sm:text-xl">{slide.text}</p>

      <div className="mt-10 flex flex-col items-stretch gap-3 sm:flex-row sm:items-center sm:gap-4">
        <Magnetic strength={9}>
          <Link
            href={slide.cta.href}
            className="group relative flex items-center justify-center gap-2.5 overflow-hidden rounded-full bg-brand-gold px-9 py-4 font-heading text-[15px] font-bold text-brand-purple-dark shadow-gold ring-1 ring-brand-purple-dark/25 transition duration-300 ease-enter hover:bg-brand-gold-deep active:scale-[0.98] active:duration-75 sm:px-10 sm:text-base"
          >
            <span className="relative z-10">{slide.cta.label}</span>
            <span aria-hidden="true" className="relative z-10 transition-transform duration-300 group-hover:translate-x-1">→</span>
            <span aria-hidden="true" className="absolute inset-y-0 -left-1/3 w-1/3 bg-white/40 blur-md transition-transform duration-700 group-hover:translate-x-[460%]" />
          </Link>
        </Magnetic>
        <Magnetic strength={9}>
          <Link
            href="/programs"
            className="group flex items-center justify-center gap-2.5 rounded-full border-2 border-white/40 bg-white/[0.06] px-9 py-4 font-heading text-[15px] font-bold text-white backdrop-blur-sm transition duration-300 ease-enter hover:border-brand-gold hover:bg-brand-gold/12 hover:text-brand-gold active:scale-[0.98] active:duration-75 sm:px-10 sm:text-base"
          >
            Explore Programmes
            <span aria-hidden="true" className="transition-transform duration-300 group-hover:translate-x-1">→</span>
          </Link>
        </Magnetic>
      </div>

      <ul className="mt-10 flex flex-wrap gap-x-7 gap-y-2.5">
        {HERO_ASSURANCES.map((a) => (
          <li key={a} className="flex items-center gap-2 font-sans text-[11px] font-medium tracking-wide text-white/65 sm:text-[12.5px]">
            <span aria-hidden="true" className="h-1 w-1 shrink-0 rounded-full bg-brand-gold" />
            {a}
          </li>
        ))}
      </ul>
    </div>
  );
}
