// ---------------------------------------------------------------------------
// WHAT EACH NETWORK NEEDS BEFORE THE UNIVERSITY CAN POST TO IT.
//
// WHY THIS FILE IS HONEST INSTEAD OF CLEVER.
//
// Every one of these platforms requires an OAuth application registered by the
// institution under its own name, reviewed by the platform, and granted the
// specific permissions listed below. None of that can be generated by this
// system, faked, or worked around — a "post to Facebook" button without a Meta
// app behind it is a button that fails, and the failure arrives after a
// graduation when somebody asks why the announcement never appeared.
//
// So the Command Centre asks this module which platforms are actually
// configured, offers only those, and says plainly what is missing for the rest.
// An administrator is never shown a destination the system cannot reach.
//
// THE REVIEW TIMES ARE REAL AND THEY MATTER FOR PLANNING. Meta's App Review for
// content publishing permissions and TikTok's Content Posting API audit both
// take weeks and both require a working privacy policy and a demonstration
// video. A university that decides in September to announce its graduation in
// October should start these applications in September.
// ---------------------------------------------------------------------------

import { PLATFORMS, type Platform } from '@/lib/social';

export interface ProviderRequirement {
  platform: Platform;
  /** The application the university registers, and where. */
  app: string;
  /** Environment variables that must be set for this platform to work. */
  env: string[];
  /** The permissions the app must be granted. */
  scopes: string[];
  /** What the university has to do that is not a form. */
  note: string;
}

export const PROVIDER_REQUIREMENTS: Record<Platform, ProviderRequirement> = {
  facebook: {
    platform: 'facebook',
    app: 'A Meta app at developers.facebook.com, with the Facebook Login and Pages products added.',
    env: ['META_APP_ID', 'META_APP_SECRET', 'META_REDIRECT_URI'],
    scopes: ['pages_manage_posts', 'pages_read_engagement', 'pages_show_list'],
    note:
      'Publishing permissions require Meta App Review. Expect it to take weeks, and to need a '
      + 'public privacy policy and a screen recording of the Command Centre in use.',
  },
  instagram: {
    platform: 'instagram',
    app: 'The same Meta app. Instagram publishing goes through the Instagram Graph API.',
    env: ['META_APP_ID', 'META_APP_SECRET', 'META_REDIRECT_URI'],
    scopes: ['instagram_basic', 'instagram_content_publish', 'pages_show_list'],
    note:
      'The Instagram account must be a Business or Creator account and must be linked to the '
      + 'Facebook Page. A personal Instagram account cannot be published to by any API.',
  },
  x: {
    platform: 'x',
    app: 'An app in the X developer portal, on a tier that permits posting.',
    env: ['X_CLIENT_ID', 'X_CLIENT_SECRET', 'X_REDIRECT_URI'],
    scopes: ['tweet.write', 'tweet.read', 'users.read', 'offline.access'],
    note:
      'The free tier has a low monthly post allowance. Check it against how often the '
      + 'University expects to publish before relying on it for announcements.',
  },
  linkedin: {
    platform: 'linkedin',
    app: 'A LinkedIn app associated with the University\'s LinkedIn Page.',
    env: ['LINKEDIN_CLIENT_ID', 'LINKEDIN_CLIENT_SECRET', 'LINKEDIN_REDIRECT_URI'],
    scopes: ['w_member_social', 'w_organization_social', 'r_organization_social'],
    note:
      'Posting as the organisation rather than as a person needs the Community Management API, '
      + 'which is requested separately and granted per page.',
  },
  youtube: {
    platform: 'youtube',
    app: 'A Google Cloud project with the YouTube Data API v3 enabled.',
    env: ['GOOGLE_CLIENT_ID', 'GOOGLE_CLIENT_SECRET', 'GOOGLE_REDIRECT_URI'],
    scopes: ['https://www.googleapis.com/auth/youtube.upload'],
    note:
      'Uploads are quota-limited and the default quota is small — roughly a handful of videos a '
      + 'day. An unverified app also caps uploads as private, which is not what a graduation '
      + 'video is for. Google verification is required before public uploads work.',
  },
  tiktok: {
    platform: 'tiktok',
    app: 'A TikTok for Developers app with the Content Posting API.',
    env: ['TIKTOK_CLIENT_KEY', 'TIKTOK_CLIENT_SECRET', 'TIKTOK_REDIRECT_URI'],
    scopes: ['video.publish', 'user.info.basic'],
    note:
      'Direct posting requires an audit. Until it passes, the API can only place a video in the '
      + 'account\'s drafts for a person to publish by hand.',
  },
  threads: {
    platform: 'threads',
    app: 'The Threads API, through the same Meta app.',
    env: ['META_APP_ID', 'META_APP_SECRET', 'META_REDIRECT_URI'],
    scopes: ['threads_basic', 'threads_content_publish'],
    note: 'Requires the Threads account to be linked to the Instagram Business account.',
  },
};

/**
 * Which platforms this deployment can actually reach.
 *
 * SERVER-SIDE ONLY. It reads process.env, which is empty in the browser — and
 * that is the right way round: the answer is about the deployment, and a client
 * that decided for itself would be deciding from nothing.
 */
export function configuredProviders(env: NodeJS.ProcessEnv = process.env): Platform[] {
  return PLATFORMS.filter((p) =>
    PROVIDER_REQUIREMENTS[p].env.every((key) => Boolean(env[key]?.trim())));
}

/** What is missing for one platform, for an error message a person can act on. */
export function missingFor(platform: Platform, env: NodeJS.ProcessEnv = process.env): string[] {
  return PROVIDER_REQUIREMENTS[platform].env.filter((key) => !env[key]?.trim());
}

/**
 * The sentence shown when somebody tries to connect a platform that is not set up.
 *
 * NAMES THE VARIABLES. "Not configured" sends an administrator to ask a
 * developer; "META_APP_ID and META_APP_SECRET are not set" sends them to the
 * Vercel dashboard, where they can fix it themselves.
 */
export function explainMissing(platform: Platform, env: NodeJS.ProcessEnv = process.env): string {
  const missing = missingFor(platform, env);
  if (missing.length === 0) return '';
  const r = PROVIDER_REQUIREMENTS[platform];
  return `${platform} is not connected to this deployment: ${missing.join(', ')} ${
    missing.length === 1 ? 'is' : 'are'} not set. ${r.app} See docs/SOCIAL-CONNECTIONS.md.`;
}
