// ---------------------------------------------------------------------------
// CHOOSING YOUR OWN PASSWORD.
//
// POST { currentPassword, newPassword } -> { ok }
//
// ---------------------------------------------------------------------------
// WHY THE ROUTE AND NOT `supabase.auth.updateUser`
// ---------------------------------------------------------------------------
//
// A browser can change its own password perfectly well. What it cannot do is
// record that it did — 090 revokes UPDATE on `profiles.password_set_at` from
// every session, at the column level, precisely so the gate cannot be skipped
// by stamping the date without changing anything.
//
// So the two have to happen together, on the server, under the service key:
// the password is changed AND the moment is recorded, or neither is. A client
// that could do the first and not the second would produce accounts that had
// changed their password and were still shown the gate; a client that could do
// the second and not the first is the hole the gate exists to close.
//
// ---------------------------------------------------------------------------
// THE CURRENT PASSWORD IS CHECKED, AND IT IS NOT CEREMONY
// ---------------------------------------------------------------------------
//
// `admin.auth.admin.updateUserById` does not ask for the old password, so
// without this a stolen or borrowed session — a shared machine, a phone left
// unlocked — could be turned into permanent ownership of the account in one
// request, locking out the person it belongs to.
//
// It is checked the only honest way: by signing in with it. This route never
// sees a stored hash and never compares one; Supabase's own auth service
// judges it, exactly as it would at the sign-in box.
// ---------------------------------------------------------------------------

import { NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { guard, audit } from '@/lib/adminAuth';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const bad = (error: string, status: number, detail?: string) =>
  NextResponse.json({ ok: false, error, ...(detail ? { detail } : {}) }, { status });

/**
 * The shortest password the University will accept.
 *
 * TWELVE, AND NOT EIGHT. The temporary password this replaces was generated by
 * the system and mailed; whatever replaces it is chosen by a person and typed
 * from memory, which is exactly the kind that is short unless a number is
 * named. Length is the only property worth insisting on — composition rules
 * produce `Password1!` and a false sense of having asked for something.
 */
const MIN_LENGTH = 12;

export async function POST(request: Request) {
  let body: Record<string, unknown>;
  try { body = await request.json(); } catch { return bad('bad-json', 400); }

  const currentPassword = String(body.currentPassword ?? '');
  const newPassword = String(body.newPassword ?? '');

  // ANY SIGNED-IN ACCOUNT MAY CHANGE ITS OWN PASSWORD, so the capability asked
  // for is one everybody holds. What makes this safe is not a capability — it
  // is that the route only ever acts on the caller's own id.
  const g = await guard(request, 'change-own-password');
  if (!g.ok) return NextResponse.json({ ok: false, error: g.error }, { status: g.status });
  const { caller, admin } = g;

  if (newPassword.length < MIN_LENGTH) {
    return bad('too-short', 400,
      `A password needs at least ${MIN_LENGTH} characters. Length is what makes one hard to `
      + 'guess — a long phrase you will remember beats a short one with symbols in it.');
  }
  if (newPassword === currentPassword) {
    return bad('same-password', 400,
      'That is the password you already have. The point of this is to replace the one the '
      + 'University generated and sent you, which is known to whatever sent it.');
  }

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !anonKey) return bad('supabase-not-configured', 500);

  // AN ACCOUNT WITH NO EMAIL ADDRESS CANNOT BE VERIFIED, so it is refused
  // rather than waved through — the check below signs in with it, and there is
  // nothing to sign in with.
  if (!caller.email) {
    return bad('no-email-on-account', 409,
      'There is no email address on your account, so your current password cannot be '
      + 'verified. Ask the Registrar to add one.');
  }

  // ---- PROVE THEY KNOW THE ONE THEY ARE REPLACING -------------------------
  const asUser = createClient(url, anonKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });
  const { data: check, error: checkError } = await asUser.auth.signInWithPassword({
    email: caller.email,
    password: currentPassword,
  });
  if (checkError || !check.session) {
    return bad('wrong-current-password', 401,
      'That is not your current password. If you no longer have it, sign out and use '
      + '“Forgot password?” to have a link sent to your email address.');
  }
  await asUser.auth.signOut();

  // ---- CHANGE IT, AND RECORD THAT IT WAS CHANGED --------------------------
  const { error: setError } = await admin.auth.admin.updateUserById(caller.id, {
    password: newPassword,
  });
  if (setError) return bad('not-changed', 409, setError.message);

  // THE STAMP. If this fails the password HAS changed, so the person is told
  // the truth rather than that nothing happened — being shown the gate again
  // is a nuisance, and believing a changed password did not change is how
  // somebody locks themselves out.
  const { error: stampError } = await admin
    .from('profiles')
    .update({ password_set_at: new Date().toISOString() })
    .eq('id', caller.id);

  await audit(admin, {
    action: 'password-changed', entityType: 'profile',
    entityId: caller.id, performedBy: caller.id,
    // NO PASSWORD, AND NOTHING SHAPED LIKE ONE — not its length, not a hint.
    // The audit trail records that it happened and when.
    details: { recorded: !stampError },
  });

  if (stampError) {
    return NextResponse.json({
      ok: true,
      warning: 'Your password was changed, but the University could not record that it was. '
        + `You may be asked to set it again. Tell the Registrar: ${stampError.message}`,
    });
  }

  return NextResponse.json({ ok: true });
}
