<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2024-04-20T18:59:07+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'America/New_York',
];
