<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2024-04-20T18:59:07+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      version_db_installed
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.2.8',
    'version_db_installed' => '20240122172319',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1713632347,
    ],
    'email' => [
        'default' => [
            'address' => 'admin@iguc.net',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
];
