<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2024-04-20T18:59:07+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'Concrete',
        ],
    ],
];
